[workspace]
resolver = "3"
members = [
    "disentangler",
    "durin",
    "dwarf2ctf",
    "findargs",
    "hansei",
    "libproc-sys",
    "print-ctf",
    "proc",
    "reify",
]

[workspace.dependencies]
anyhow = "1.0"
camino = "1.2"
assert_cmd = "2.0"
bindgen = { version = "0.72", default-features = false }
clap = { version = "4.5.51", features = ["derive"] }
console = "0.16"
durin = { path = "durin", version = "0.1.0" }
fallible-iterator = "0.3.0"
flate2 = "1.1.5"
gimli = { version = "0.32", features = ["fallible-iterator"] }
goblin = "0.10.3"
humantime = "2.3"
libproc-sys = { path = "libproc-sys", version = "0.1.0" }
memmap2 = "0.9.9"
petgraph = "0.7"
predicates = "3.1"
proc = { path = "proc", version = "0.1.0" }
rangemap = "1.7.0"
reify = { path = "reify", version = "0.1.0" }
regex = "1.12"
rustc-demangle = "0.1.27"
scroll = "0.13.0"
semver = "1.0"
tempfile = "3.14"
thiserror = "2.0.17"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
