[package]
name = "unwind"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Stack unwinding for a core-dump target using DWARF .eh_frame CFI"

[dependencies]
anyhow.workspace = true
gimli.workspace = true
goblin.workspace = true
proc.workspace = true
rustc-demangle.workspace = true

[dev-dependencies]
tempfile.workspace = true
testrun = { workspace = true }
