[package]
name = "hansei"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
durin = { workspace = true }
gimli = { workspace = true }
goblin = { workspace = true }
proc = { workspace = true }
regex = { workspace = true }
rustc-demangle = { workspace = true }
semver = { workspace = true }
