= Hansei

> https://en.wikipedia.org/wiki/Hansei[Hansei] (反省; "self-reflection") is a central idea in Japanese culture, meaning
to acknowledge one's own mistake and to pledge improvement.

A tool to inspect where we have erred with `tokio`. Currently a proof-of-concept, expect bugs.

Today `hansei` only supports the `tokio` runtime as configured in `omicron`, unstable features enabled, versions
1.48 and 1.49. The CTF file must be generated by the `dwarf2ctf` tool in this workspace.

WARNING: DO NOT USE RUN THIS AGAINST A PROCESS YOU CARE ABOUT.

== Usage

First, build a release binary with `debug = true` set. I haven't run down why dev builds don't work, I wouldn't expect
the struct layout to be different for them. The CTF can be applied to any binary that uses the same `tokio` version and
features, i.e., you can use the same file for both `nexus` and `sled-agent`.

To generate the CTF file, execute:

[source,shell]
====
cargo run --release --bin dwarf2ctf -- ${PATH_TO_BINARY} --ctf-out tokio.ctf -t 'tokio::runtime::context::Context' -t 'tokio::runtime::task::core::Trailer' -t 'core::panic::location::Location' -t 'alloc::sync::Arc<tokio::runtime::park::Inner, alloc::alloc::Global>'
====

There are two subcommands:

* `dump` will output the state of the `tokio` runtime scheduler and thread-local contexts from either a core dump or
a live process.
* `poll` will attach to the process, periodically pausing it at to read the `tokio` state, printing a brief summary.

Backtraces for all threads are captured by default by `dump`, though only displayed for active workers. This is quite
slow currently and disabled for `poll`.

== Why generate CTF for these types?

To give a bit of explanation on why these types are being included. Any type that is linked to a member of a type
requested will be included in the CTF. `tokio` and `std::task::Waker` are a bit unusual for Rust as they will sometimes
use an bare offset or `void*` to access a value. Types referenced this way do not have a cross-reference in the DWARF,
so we need to manually tell `dwarf2ctf` to include them.

* `tokio::runtime::context::Context`: The thread-local context for workers. Pulls in the vast majority of types we
need, including the scheduler.
* `tokio::runtime::task::core::Trailer`: The cold data stored at the end of a task. The offset to this is stored in the
`TaskHeader`. Contains the `Waker` for the task.
* `core::panic::location::Location`: The source location that generated the future. Also stored as an offset from the
`TaskHeader`.
* `alloc::sync::Arc<tokio::runtime::park::Inner, alloc::alloc::Global>`: One of the types potentially stored as a
`void*` in a `Waker`. Tracks the state of a thread.

