[package]
name = "dwarf2ctf"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
flate2 = { workspace = true }
gimli = { workspace = true }
goblin = { workspace = true }
memmap2 = { workspace = true }
petgraph = { workspace = true }
scroll = { workspace = true }

[dev-dependencies]
assert_cmd = { workspace = true }
checkctf = { workspace = true }
predicates = { workspace = true }
tempfile = { workspace = true }
