[package]
name = "durin"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = { workspace = true } # FIXME
flate2 = { workspace = true }
gimli = { workspace = true }
goblin = { workspace = true }
proc = { workspace = true }
scroll = { workspace = true }
scroll_derive = { workspace = true }
thiserror = { workspace = true }
