[package]
name = "reify"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Renders values from a target's memory using the layouts in a tokio-info bundle"

[dependencies]
foldhash.workspace = true
hansei-bundle = { workspace = true }
proc = { workspace = true }
rayon = { workspace = true }
rustc-demangle = { workspace = true }
thiserror = { workspace = true }
