//! Emitting a [`Program`] as a complete fixture source file.
//!
//! The emitted program follows the hand-written fixtures' shape
//! (`unordered.rs`, `joinset.rs`): every running body registers what it
//! built with `census_expect` at the addresses it built it, reports in
//! on a shared channel, and parks forever; `main` counts every body's
//! report before printing `READY`, so a capture taken at the marker
//! sees every registration and every park. All the primitives pend
//! forever — the notify is never notified, the oneshot senders are
//! leaked, the semaphore has no permits, the timer deadlines are years
//! out.
//!
//! Registration invariants the emitter maintains:
//!
//! - A held coroutine registers the address of the *slot* the scan
//!   enters through — the value's own place in the local, spelled as a
//!   field path (`&v0.0.inner`); an `Option` step goes through
//!   `.as_ref().unwrap()`, whose result is already a reference.
//! - A never-polled holder's argument coroutines register `held_in`
//!   keyed by the holder's slot, because they have no address the
//!   fixture can name.
//! - Locals are registered *after* every local is built and consumed
//!   *after* the park, so each sits in the coroutine frame, at its
//!   registered address, for the whole parked lifetime.
//!
//! [`Mode::Churn`] emits the same tree as a workload that never
//! settles: every park completes after a short delay (a churner task
//! notifies the notify and feeds the semaphore, timers are
//! milliseconds out, oneshot senders fire from spawned tasks), every
//! body completes and is respawned by a supervisor loop, and nothing
//! registers — a capture is taken at an arbitrary instant, so no
//! omission or liveness claim is checkable and the oracle is safety
//! only. The program prints `CHURNING` once the supervisors are
//! spawned (a liveness marker for the capture script, not a
//! quiescence handshake — there is none).

use crate::tree::{Body, BodyKind, Leaf, Park, ParkPoint, Program, Value, total_bodies};

/// How the emitted program behaves at runtime. The tree is the same
/// either way; the mode decides whether it parks forever under a
/// registry or churns forever without one.
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Mode {
    /// Every future pends forever; ground truth is registered; `READY`
    /// marks quiescence. The registry-diff fixture shape.
    Parked,
    /// Every future completes and respawns; nothing is registered.
    Churn,
}

/// A short, per-site completion delay, derived from the site's id so
/// churn programs interleave rather than march in lockstep.
fn churn_ms(id: usize) -> u64 {
    5 + (id as u64 * 13) % 70
}

/// Which support items and imports the program actually needs.
#[derive(Default)]
struct Uses {
    wrap: bool,
    sel: [bool; 2], // GfSel2, GfSel3
    joi: [bool; 2], // GfJoi2, GfJoi3
    oneshot: bool,
    timer: bool,
    unordered: bool,
    join_set: bool,
    boxed: bool,
    holder: bool,
}

pub fn emit(p: &Program, mode: Mode) -> String {
    let churn = mode == Mode::Churn;
    let mut uses = Uses::default();
    let mut leaves: Vec<(usize, Park)> = Vec::new();
    let mut holders: Vec<usize> = Vec::new();
    let mut bodies: Vec<&Body> = Vec::new();
    for d in &p.drivers {
        collect_body(d, &mut uses, &mut leaves, &mut holders, &mut bodies);
    }
    leaves.sort_by_key(|&(id, _)| id);
    holders.sort_unstable();
    bodies.sort_by_key(|b| b.id);

    let mut s = String::new();
    let flag = if churn { " --churn" } else { "" };
    let blurb = if churn {
        "//! A random combinator tree over the census's shapes that never\n\
         //! settles: every future completes shortly and is rebuilt, so a\n\
         //! capture at any instant sees the walk's shapes mid-flight.\n"
    } else {
        "//! A random combinator tree over the census's shapes, registering\n\
         //! ground truth for the registry diff as it builds each value.\n"
    };
    s.push_str(&format!(
        "//! Generated by genfix from seed {seed}; regenerate with\n\
         //! `genfix --seed {seed}{flag}` rather than editing.\n\
         //!\n\
         {blurb}\
         #![allow(dead_code)]\n\n",
        seed = p.seed
    ));

    // Imports, following the fixtures' std-first ordering. Churn mode
    // sleeps everywhere — the churner, the timers, the delayed oneshot
    // senders — so Duration is unconditional there.
    let mut std_lines: Vec<&str> = Vec::new();
    if uses.holder || uses.boxed || uses.sel.iter().chain(&uses.joi).any(|&b| b) {
        std_lines.push("use std::future::Future;");
    }
    if uses.boxed || uses.sel.iter().chain(&uses.joi).any(|&b| b) {
        std_lines.push("use std::pin::Pin;");
    }
    std_lines.push("use std::sync::Arc;");
    if uses.sel.iter().chain(&uses.joi).any(|&b| b) {
        std_lines.push("use std::task::{Context, Poll};");
    }
    if uses.timer || churn {
        std_lines.push("use std::time::Duration;");
    }
    for l in std_lines {
        s.push_str(l);
        s.push('\n');
    }
    s.push('\n');
    if uses.unordered {
        s.push_str("use futures::stream::{FuturesUnordered, StreamExt};\n");
    }
    if !churn {
        s.push_str("use test_programs::census_expect;\n");
    }
    let sync = match (churn, uses.oneshot) {
        (false, true) => "use tokio::sync::{Notify, Semaphore, mpsc, oneshot};\n",
        (false, false) => "use tokio::sync::{Notify, Semaphore, mpsc};\n",
        (true, true) => "use tokio::sync::{Notify, Semaphore, oneshot};\n",
        (true, false) => "use tokio::sync::{Notify, Semaphore};\n",
    };
    s.push_str(sync);
    if uses.join_set {
        s.push_str("use tokio::task::JoinSet;\n");
    }
    s.push('\n');

    if !churn {
        s.push_str(&format!(
            "/// Every running body reports in before main declares readiness.\n\
             const TOTAL_BODIES: usize = {};\n\n",
            total_bodies(p)
        ));
    }

    emit_support(&uses, &mut s);
    for &(id, park) in &leaves {
        emit_leaf(id, park, mode, &mut s);
    }
    for &id in &holders {
        s.push_str(&format!(
            "/// Holds another future as an argument across its own park — the\n\
             /// one shape whose chain still has a future to find while unpolled.\n\
             async fn holder_{id:02}<F: Future<Output = u64>>(inner: F, notify: Arc<Notify>) -> u64 {{\n\
             \x20   notify.notified().await;\n\
             \x20   inner.await\n\
             }}\n\n"
        ));
    }
    for b in &bodies {
        emit_body(b, mode, &mut s);
    }
    emit_main(p, mode, &mut s);
    s
}

fn collect_body<'a>(
    b: &'a Body,
    uses: &mut Uses,
    leaves: &mut Vec<(usize, Park)>,
    holders: &mut Vec<usize>,
    bodies: &mut Vec<&'a Body>,
) {
    bodies.push(b);
    for v in &b.locals {
        collect_value(v, uses, leaves, holders, bodies);
    }
    match &b.park {
        ParkPoint::Primitive(p) => note_park(*p, uses),
        ParkPoint::Combinator { select, arms } => {
            let idx = arms - 2;
            if *select {
                uses.sel[idx] = true;
            } else {
                uses.joi[idx] = true;
            }
        }
        ParkPoint::PolledSet { child, .. } => {
            uses.unordered = true;
            collect_body(child, uses, leaves, holders, bodies);
        }
    }
}

fn collect_value<'a>(
    v: &'a Value,
    uses: &mut Uses,
    leaves: &mut Vec<(usize, Park)>,
    holders: &mut Vec<usize>,
    bodies: &mut Vec<&'a Body>,
) {
    match v {
        Value::Leaf(l) => {
            note_park(l.park, uses);
            leaves.push((l.id, l.park));
        }
        Value::Holder { id, arg } => {
            uses.holder = true;
            holders.push(*id);
            collect_value(arg, uses, leaves, holders, bodies);
        }
        Value::BoxedDyn(l) => {
            uses.boxed = true;
            note_park(l.park, uses);
            leaves.push((l.id, l.park));
        }
        Value::Tuple(inner, _) | Value::Opt(inner) | Value::Wrap(inner, _) => {
            if matches!(v, Value::Wrap(..)) {
                uses.wrap = true;
            }
            collect_value(inner, uses, leaves, holders, bodies);
        }
        Value::Sel(arms) | Value::Joi(arms) => {
            let idx = arms.len() - 2;
            if matches!(v, Value::Sel(_)) {
                uses.sel[idx] = true;
            } else {
                uses.joi[idx] = true;
            }
            for a in arms {
                collect_value(a, uses, leaves, holders, bodies);
            }
        }
        Value::Set { child, .. } => {
            uses.unordered = true;
            note_park(child.park, uses);
            leaves.push((child.id, child.park));
        }
        Value::JSet { members } => {
            uses.join_set = true;
            for m in members {
                collect_body(m, uses, leaves, holders, bodies);
            }
        }
    }
}

fn note_park(p: Park, uses: &mut Uses) {
    match p {
        Park::Oneshot => uses.oneshot = true,
        Park::Timer => uses.timer = true,
        Park::Notify | Park::Semaphore => {}
    }
}

/// The hand-written support types: a non-Future wrapper struct and the
/// select/join combinators whose Future impls the chain walk has to
/// pass through.
fn emit_support(uses: &Uses, s: &mut String) {
    if uses.wrap {
        s.push_str(
            "/// A hand-written non-Future struct the scan must descend through.\n\
             struct GfWrap<F> {\n\
             \x20   inner: F,\n\
             \x20   tag: u64,\n\
             }\n\n",
        );
    }
    for (idx, &used) in uses.sel.iter().enumerate() {
        if used {
            emit_sel(idx + 2, s);
        }
    }
    for (idx, &used) in uses.joi.iter().enumerate() {
        if used {
            emit_joi(idx + 2, s);
        }
    }
}

const ARMS: [&str; 3] = ["a", "b", "c"];

fn generics(n: usize) -> (String, String, String) {
    let names: Vec<String> = (0..n).map(|i| ARMS[i].to_uppercase()).collect();
    let plain = names.join(", ");
    let bounded = names
        .iter()
        .map(|g| format!("{g}: Future<Output = u64>"))
        .collect::<Vec<_>>()
        .join(", ");
    (plain, bounded, names.join(""))
}

fn emit_sel(n: usize, s: &mut String) {
    let (plain, bounded, _) = generics(n);
    s.push_str(&format!(
        "/// A hand-written select: ready when any arm is.\n\
         struct GfSel{n}<{plain}> {{\n"
    ));
    for arm in &ARMS[..n] {
        s.push_str(&format!("    {arm}: {},\n", arm.to_uppercase()));
    }
    s.push_str("}\n\n");
    s.push_str(&format!(
        "impl<{bounded}> Future for GfSel{n}<{plain}> {{\n\
         \x20   type Output = u64;\n\
         \x20   fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<u64> {{\n\
         \x20       // SAFETY: no arm is ever moved out of the pinned struct.\n\
         \x20       let this = unsafe {{ self.get_unchecked_mut() }};\n"
    ));
    for arm in &ARMS[..n] {
        s.push_str(&format!(
            "        if let Poll::Ready(v) = unsafe {{ Pin::new_unchecked(&mut this.{arm}) }}.poll(cx) {{\n\
             \x20           return Poll::Ready(v);\n\
             \x20       }}\n"
        ));
    }
    s.push_str("        Poll::Pending\n    }\n}\n\n");
}

fn emit_joi(n: usize, s: &mut String) {
    let (plain, bounded, _) = generics(n);
    s.push_str(&format!(
        "/// A hand-written join: ready when every arm is.\n\
         struct GfJoi{n}<{plain}> {{\n"
    ));
    for arm in &ARMS[..n] {
        s.push_str(&format!("    {arm}: {},\n", arm.to_uppercase()));
    }
    for arm in &ARMS[..n] {
        s.push_str(&format!("    got_{arm}: Option<u64>,\n"));
    }
    s.push_str("}\n\n");
    s.push_str(&format!(
        "impl<{bounded}> Future for GfJoi{n}<{plain}> {{\n\
         \x20   type Output = u64;\n\
         \x20   fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<u64> {{\n\
         \x20       // SAFETY: no arm is ever moved out of the pinned struct.\n\
         \x20       let this = unsafe {{ self.get_unchecked_mut() }};\n"
    ));
    for arm in &ARMS[..n] {
        s.push_str(&format!(
            "        if this.got_{arm}.is_none() {{\n\
             \x20           if let Poll::Ready(v) = unsafe {{ Pin::new_unchecked(&mut this.{arm}) }}.poll(cx) {{\n\
             \x20               this.got_{arm} = Some(v);\n\
             \x20           }}\n\
             \x20       }}\n"
        ));
    }
    let all = ARMS[..n]
        .iter()
        .map(|a| format!("this.got_{a}.is_some()"))
        .collect::<Vec<_>>()
        .join(" && ");
    let sum = ARMS[..n]
        .iter()
        .map(|a| format!("this.got_{a}.unwrap_or(0)"))
        .collect::<Vec<_>>()
        .join(" + ");
    s.push_str(&format!(
        "        if {all} {{\n\
         \x20           return Poll::Ready({sum});\n\
         \x20       }}\n\
         \x20       Poll::Pending\n\
         \x20   }}\n\
         }}\n\n"
    ));
}

/// The statements a park primitive awaits, per mode. In churn mode
/// every one completes: the churner notifies and feeds the semaphore,
/// the timer is milliseconds out, and the oneshot's sender fires from
/// a spawned task instead of being leaked. `id` names the site (a leaf
/// id or a body id) for the delay derivation and the oneshot bindings.
fn park_stmts(park: Park, id: usize, mode: Mode) -> String {
    let churn = mode == Mode::Churn;
    match park {
        Park::Notify => "notify.notified().await;".to_string(),
        Park::Semaphore if churn => {
            // Consume the permit for real (parked mode's `let _` would
            // return it) so semaphore sites keep contending with the
            // churner's feed rate rather than free-running.
            "sem.acquire().await.expect(\"the semaphore is never closed\").forget();".to_string()
        }
        Park::Semaphore => "let _ = sem.acquire().await;".to_string(),
        Park::Timer if churn => format!(
            "tokio::time::sleep(Duration::from_millis({})).await;",
            churn_ms(id)
        ),
        Park::Timer => "tokio::time::sleep(Duration::from_secs(3_000_000)).await;".to_string(),
        Park::Oneshot if churn => format!(
            "let (tx_{id:02}, rx_{id:02}) = oneshot::channel::<u64>();\n\
             \x20   tokio::spawn(async move {{\n\
             \x20       tokio::time::sleep(Duration::from_millis({ms})).await;\n\
             \x20       let _ = tx_{id:02}.send(0);\n\
             \x20   }});\n\
             \x20   let _ = rx_{id:02}.await;",
            ms = churn_ms(id)
        ),
        Park::Oneshot => format!(
            "let (tx_{id:02}, rx_{id:02}) = oneshot::channel::<u64>();\n\
             \x20   std::mem::forget(tx_{id:02});\n\
             \x20   let _ = rx_{id:02}.await;"
        ),
    }
}

fn emit_leaf(id: usize, park: Park, mode: Mode, s: &mut String) {
    let sig = match park {
        Park::Notify => "notify: Arc<Notify>",
        Park::Semaphore => "sem: Arc<Semaphore>",
        Park::Oneshot | Park::Timer => "",
    };
    let body = park_stmts(park, id, mode);
    s.push_str(&format!(
        "async fn leaf_{id:02}({sig}) -> u64 {{\n\
         \x20   {body}\n\
         \x20   {id}\n\
         }}\n\n"
    ));
}

/// The place-path a registration names: the expression so far, and
/// whether it already denotes a reference (an `.as_ref().unwrap()`
/// step does; a field step resets it).
#[derive(Clone)]
struct Path {
    expr: String,
    is_ref: bool,
}

impl Path {
    fn root(name: &str) -> Self {
        Path {
            expr: name.to_string(),
            is_ref: false,
        }
    }

    fn field(&self, f: &str) -> Self {
        Path {
            expr: format!("{}.{f}", self.expr),
            is_ref: false,
        }
    }

    fn through_option(&self) -> Self {
        Path {
            expr: format!("{}.as_ref().unwrap()", self.expr),
            is_ref: true,
        }
    }

    fn addr(&self) -> String {
        if self.is_ref {
            format!("{} as *const _ as u64", self.expr)
        } else {
            format!("&{} as *const _ as u64", self.expr)
        }
    }
}

fn body_fn_name(b: &Body) -> String {
    let prefix = match b.kind {
        BodyKind::Driver => "driver",
        BodyKind::SetChild => "child",
        BodyKind::Member => "member",
    };
    format!("{prefix}_{:02}", b.id)
}

/// Whether a body (directly or through calls it makes) touches the
/// shared notify / semaphore, to underscore unused parameters.
fn body_needs(b: &Body) -> (bool, bool) {
    fn leaf_needs(l: &Leaf) -> (bool, bool) {
        (l.park == Park::Notify, l.park == Park::Semaphore)
    }
    fn value_needs(v: &Value) -> (bool, bool) {
        match v {
            Value::Leaf(l) | Value::BoxedDyn(l) => leaf_needs(l),
            // The holder call itself passes the notify.
            Value::Holder { arg, .. } => {
                let (_, s) = value_needs(arg);
                (true, s)
            }
            Value::Tuple(i, _) | Value::Opt(i) | Value::Wrap(i, _) => value_needs(i),
            Value::Sel(arms) | Value::Joi(arms) => join_needs(arms.iter().map(value_needs)),
            Value::Set { child, .. } => leaf_needs(child),
            // Spawning a member passes both.
            Value::JSet { .. } => (true, true),
        }
    }
    fn join_needs(it: impl Iterator<Item = (bool, bool)>) -> (bool, bool) {
        it.fold((false, false), |(n, s), (n2, s2)| (n || n2, s || s2))
    }
    let locals = join_needs(b.locals.iter().map(value_needs));
    let park = match &b.park {
        ParkPoint::Primitive(p) => (*p == Park::Notify, *p == Park::Semaphore),
        // pending() arms touch neither.
        ParkPoint::Combinator { .. } => (false, false),
        // Constructing the child instances passes both.
        ParkPoint::PolledSet { .. } => (true, true),
    };
    (locals.0 || park.0, locals.1 || park.1)
}

/// The expression constructing a leaf instance. A oneshot leaf takes
/// no argument — it makes (and leaks) its channel inside its body, so
/// an unpolled instance's frame carries no `Receiver`. A receiver held
/// in a frame is a census find of its own, and a leaf argument would
/// put one at addresses no fixture can register (inside a set node's
/// allocation).
fn leaf_call(l: &Leaf) -> String {
    match l.park {
        Park::Notify => format!("leaf_{:02}(notify.clone())", l.id),
        Park::Semaphore => format!("leaf_{:02}(sem.clone())", l.id),
        Park::Timer | Park::Oneshot => format!("leaf_{:02}()", l.id),
    }
}

/// The arguments a body call passes: churn bodies have no readiness
/// channel to thread through.
fn body_args(mode: Mode) -> &'static str {
    match mode {
        Mode::Parked => "started.clone(), notify.clone(), sem.clone()",
        Mode::Churn => "notify.clone(), sem.clone()",
    }
}

fn value_expr(v: &Value, mode: Mode) -> String {
    match v {
        Value::Leaf(l) => leaf_call(l),
        Value::Holder { id, arg } => {
            let inner = value_expr(arg, mode);
            format!("holder_{id:02}({inner}, notify.clone())")
        }
        Value::BoxedDyn(l) => format!(
            "Box::pin({}) as Pin<Box<dyn Future<Output = u64> + Send>>",
            leaf_call(l)
        ),
        Value::Tuple(inner, k) => format!("({}, {k}u64)", value_expr(inner, mode)),
        Value::Opt(inner) => format!("Some({})", value_expr(inner, mode)),
        Value::Wrap(inner, tag) => format!(
            "GfWrap {{ inner: {}, tag: {tag} }}",
            value_expr(inner, mode)
        ),
        Value::Sel(arms) => {
            let fields = arms
                .iter()
                .enumerate()
                .map(|(i, a)| format!("{}: {}", ARMS[i], value_expr(a, mode)))
                .collect::<Vec<_>>()
                .join(", ");
            format!("GfSel{} {{ {fields} }}", arms.len())
        }
        Value::Joi(arms) => {
            let fields = arms
                .iter()
                .enumerate()
                .map(|(i, a)| format!("{}: {}", ARMS[i], value_expr(a, mode)))
                .collect::<Vec<_>>()
                .join(", ");
            let none = arms
                .iter()
                .enumerate()
                .map(|(i, _)| format!("got_{}: None", ARMS[i]))
                .collect::<Vec<_>>()
                .join(", ");
            format!("GfJoi{} {{ {fields}, {none} }}", arms.len())
        }
        Value::Set { count, child } => format!(
            "(0..{count}).map(|_| {}).collect::<FuturesUnordered<_>>()",
            leaf_call(child)
        ),
        Value::JSet { members } => {
            let mut b = String::from("{\n        let mut js = JoinSet::new();\n");
            for m in members {
                b.push_str(&format!(
                    "        js.spawn({}({}));\n",
                    body_fn_name(m),
                    body_args(mode)
                ));
            }
            b.push_str("        js\n    }");
            b
        }
    }
}

/// Every leaf id reachable in a holder's argument, for `held_in`.
fn arg_leaves(v: &Value, out: &mut Vec<usize>) {
    match v {
        Value::Leaf(l) => out.push(l.id),
        Value::Tuple(i, _) | Value::Opt(i) | Value::Wrap(i, _) => arg_leaves(i, out),
        Value::Sel(arms) | Value::Joi(arms) => arms.iter().for_each(|a| arg_leaves(a, out)),
        Value::Holder { .. } | Value::BoxedDyn(_) | Value::Set { .. } | Value::JSet { .. } => {
            unreachable!("argument context excludes these")
        }
    }
}

fn reg_stmts(v: &Value, path: &Path, out: &mut String) {
    match v {
        Value::Leaf(l) => out.push_str(&format!(
            "    census_expect::held({}, \"leaf_{:02}\");\n",
            path.addr(),
            l.id
        )),
        Value::Holder { id, arg } => {
            out.push_str(&format!(
                "    census_expect::held({}, \"holder_{id:02}\");\n",
                path.addr()
            ));
            let mut inner = Vec::new();
            arg_leaves(arg, &mut inner);
            for leaf in inner {
                out.push_str(&format!(
                    "    census_expect::held_in({}, \"leaf_{leaf:02}\");\n",
                    path.addr()
                ));
            }
        }
        Value::BoxedDyn(l) => out.push_str(&format!(
            "    census_expect::held({}, \"leaf_{:02}\");\n",
            path.addr(),
            l.id
        )),
        Value::Tuple(inner, _) => reg_stmts(inner, &path.field("0"), out),
        Value::Opt(inner) => reg_stmts(inner, &path.through_option(), out),
        Value::Wrap(inner, _) => reg_stmts(inner, &path.field("inner"), out),
        // Though it implements Future, a combinator held in a body's
        // frame is not a census row — the locals scan descends through
        // it like any aggregate, and only the coroutines inside are
        // finds. (Inside a *held future's* frame the chain machinery
        // does record it, which is why holder arguments are bare
        // leaves.)
        Value::Sel(arms) | Value::Joi(arms) => {
            for (i, a) in arms.iter().enumerate() {
                reg_stmts(a, &path.field(ARMS[i]), out);
            }
        }
        Value::Set { count, .. } => out.push_str(&format!(
            "    census_expect::set({}, {count});\n",
            path.addr()
        )),
        Value::JSet { members } => out.push_str(&format!(
            "    census_expect::join_set({}, {});\n",
            path.addr(),
            members.len()
        )),
    }
}

/// Consume a local after the park so it stays live across it. Every
/// shape ends in a use: futures are awaited, sets counted, join sets
/// measured, scalars added.
fn consume_stmts(v: &Value, expr: String, tmp: &mut usize, out: &mut String) {
    match v {
        Value::Leaf(_) | Value::Holder { .. } | Value::BoxedDyn(_) => {
            out.push_str(&format!("    sum = sum.wrapping_add({expr}.await);\n"));
        }
        Value::Tuple(inner, _) => {
            consume_stmts(inner, format!("{expr}.0"), tmp, out);
            out.push_str(&format!("    sum = sum.wrapping_add({expr}.1);\n"));
        }
        Value::Opt(inner) => {
            let t = format!("t{tmp}");
            *tmp += 1;
            out.push_str(&format!("    let {t} = {expr}.unwrap();\n"));
            consume_stmts(inner, t, tmp, out);
        }
        Value::Wrap(inner, _) => {
            consume_stmts(inner, format!("{expr}.inner"), tmp, out);
            out.push_str(&format!("    sum = sum.wrapping_add({expr}.tag);\n"));
        }
        Value::Sel(arms) | Value::Joi(arms) => {
            for (i, a) in arms.iter().enumerate() {
                consume_stmts(a, format!("{expr}.{}", ARMS[i]), tmp, out);
            }
        }
        Value::Set { .. } => {
            out.push_str(&format!(
                "    sum = sum.wrapping_add({expr}.count().await as u64);\n"
            ));
        }
        Value::JSet { .. } => {
            out.push_str(&format!(
                "    sum = sum.wrapping_add({expr}.len() as u64);\n"
            ));
        }
    }
}

fn emit_body(b: &Body, mode: Mode, s: &mut String) {
    let churn = mode == Mode::Churn;
    let name = body_fn_name(b);
    let (need_notify, need_sem) = body_needs(b);
    let notify_arg = if need_notify { "notify" } else { "_notify" };
    let sem_arg = if need_sem { "sem" } else { "_sem" };
    if churn {
        s.push_str(&format!(
            "async fn {name}(\n\
             \x20   {notify_arg}: Arc<Notify>,\n\
             \x20   {sem_arg}: Arc<Semaphore>,\n\
             ) -> u64 {{\n"
        ));
    } else {
        s.push_str(&format!(
            "async fn {name}(\n\
             \x20   started: mpsc::UnboundedSender<()>,\n\
             \x20   {notify_arg}: Arc<Notify>,\n\
             \x20   {sem_arg}: Arc<Semaphore>,\n\
             ) -> u64 {{\n"
        ));
    }

    // Locals.
    for (i, v) in b.locals.iter().enumerate() {
        let expr = value_expr(v, mode);
        s.push_str(&format!("    let v{i} = {expr};\n"));
    }
    if let ParkPoint::PolledSet { count, child } = &b.park {
        s.push_str(&format!(
            "    let mut park_set: FuturesUnordered<_> = (0..{count})\n\
             \x20       .map(|_| {}({}))\n\
             \x20       .collect();\n",
            body_fn_name(child),
            body_args(mode)
        ));
    }
    if !churn {
        // Ground truth for the census diff: everything built above, at
        // the slot it sits in. A churn body claims nothing — by the
        // time a capture reads a registration it may describe a value
        // three respawns gone.
        if b.kind != BodyKind::SetChild {
            s.push_str(&format!("    census_expect::task(\"{name}\");\n"));
        }
        for (i, v) in b.locals.iter().enumerate() {
            reg_stmts(v, &Path::root(&format!("v{i}")), s);
        }
        if let ParkPoint::PolledSet { count, .. } = &b.park {
            s.push_str(&format!(
                "    census_expect::set(&park_set as *const _ as u64, {count});\n"
            ));
        }
        s.push_str("    started.send(()).expect(\"main counts readiness\");\n");
    }

    // The park, with the locals live across it.
    let has_consumption = !b.locals.is_empty();
    match &b.park {
        ParkPoint::Primitive(p) => {
            // park_stmts' continuation lines carry their own 4-space
            // base indent; only the first line needs one added.
            s.push_str(&format!("    {}\n", park_stmts(*p, b.id, mode)));
            let mutability = if has_consumption { "mut " } else { "" };
            s.push_str(&format!("    let {mutability}sum: u64 = 0;\n"));
        }
        // Awaited as an rvalue: the chain passes through the
        // hand-written combinator. Parked mode's arms are zero-sized
        // pending()s — a chain frame's zero-sized locals produce no
        // census rows, the one spelling that leaves nothing to
        // register. Churn mode registers nothing anyway, so its arms
        // are sized sleeps that complete — chain-frame rows the parked
        // corpus cannot show, at instants only a churn capture sees.
        ParkPoint::Combinator { select, arms } => {
            let arm_expr = |i: usize| {
                if churn {
                    format!(
                        "async {{ tokio::time::sleep(Duration::from_millis({})).await; {i}u64 }}",
                        churn_ms(b.id + i + 1)
                    )
                } else {
                    "std::future::pending::<u64>()".to_string()
                }
            };
            let fields = (0..*arms)
                .map(|i| format!("{}: {}", ARMS[i], arm_expr(i)))
                .collect::<Vec<_>>()
                .join(", ");
            let expr = if *select {
                format!("GfSel{arms} {{ {fields} }}")
            } else {
                let none = (0..*arms)
                    .map(|i| format!("got_{}: None", ARMS[i]))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("GfJoi{arms} {{ {fields}, {none} }}")
            };
            let mutability = if has_consumption { "mut " } else { "" };
            s.push_str(&format!("    let {mutability}sum: u64 = {expr}.await;\n"));
        }
        ParkPoint::PolledSet { .. } => {
            s.push_str(
                "    let mut sum: u64 = 0;\n\
                 \x20   while let Some(v) = park_set.next().await {\n\
                 \x20       sum = sum.wrapping_add(v);\n\
                 \x20   }\n",
            );
        }
    }

    // Consumption: every local used after the park.
    let mut tmp = 0usize;
    for (i, v) in b.locals.iter().enumerate() {
        consume_stmts(v, format!("v{i}"), &mut tmp, s);
    }
    s.push_str("    sum\n}\n\n");
}

fn emit_main(p: &Program, mode: Mode, s: &mut String) {
    if mode == Mode::Churn {
        emit_churn_main(p, s);
        return;
    }
    s.push_str(
        "fn main() {\n\
         \x20   test_programs::allow_any_tracer();\n\
         \n\
         \x20   let mut builder = test_programs::Builder::new_multi_thread();\n\
         \x20   builder.worker_threads(2);\n\
         \x20   test_programs::run_builder(&mut builder, async {\n\
         \x20       let (started_tx, mut started_rx) = mpsc::unbounded_channel::<()>();\n\
         \x20       // Never notified, and never granted a permit: every leaf\n\
         \x20       // parks for good.\n\
         \x20       let notify = Arc::new(Notify::new());\n\
         \x20       let sem = Arc::new(Semaphore::new(0));\n\
         \n",
    );
    for (i, d) in p.drivers.iter().enumerate() {
        s.push_str(&format!(
            "        let _t{i} = tokio::spawn({}(started_tx.clone(), notify.clone(), sem.clone()));\n",
            body_fn_name(d)
        ));
    }
    s.push_str(
        "        drop(started_tx);\n\
         \n\
         \x20       for _ in 0..TOTAL_BODIES {\n\
         \x20           started_rx.recv().await.expect(\"every body reports in\");\n\
         \x20       }\n\
         \x20       println!(\"READY\");\n\
         \x20       std::future::pending::<()>().await\n\
         \x20   })\n\
         }\n",
    );
}

/// Churn main: a churner task keeps every park primitive completing,
/// each driver runs under a supervisor loop that rebuilds it the
/// moment it finishes, and `CHURNING` is printed as soon as the
/// supervisors are spawned — a liveness marker only; there is no
/// quiescent state to wait for, which is the point.
fn emit_churn_main(p: &Program, s: &mut String) {
    s.push_str(
        "fn main() {\n\
         \x20   test_programs::allow_any_tracer();\n\
         \n\
         \x20   let mut builder = test_programs::Builder::new_multi_thread();\n\
         \x20   builder.worker_threads(2);\n\
         \x20   test_programs::run_builder(&mut builder, async {\n\
         \x20       let notify = Arc::new(Notify::new());\n\
         \x20       let sem = Arc::new(Semaphore::new(0));\n\
         \n\
         \x20       // The churner: whatever is parked on the notify or the\n\
         \x20       // semaphore right now gets moving again a few\n\
         \x20       // milliseconds from now, forever.\n\
         \x20       {\n\
         \x20           let notify = notify.clone();\n\
         \x20           let sem = sem.clone();\n\
         \x20           tokio::spawn(async move {\n\
         \x20               loop {\n\
         \x20                   tokio::time::sleep(Duration::from_millis(3)).await;\n\
         \x20                   notify.notify_waiters();\n\
         \x20                   sem.add_permits(4);\n\
         \x20               }\n\
         \x20           });\n\
         \x20       }\n\
         \n",
    );
    for (i, d) in p.drivers.iter().enumerate() {
        s.push_str(&format!(
            "        let notify_{i} = notify.clone();\n\
             \x20       let sem_{i} = sem.clone();\n\
             \x20       let _t{i} = tokio::spawn(async move {{\n\
             \x20           loop {{\n\
             \x20               let _ = {}(notify_{i}.clone(), sem_{i}.clone()).await;\n\
             \x20           }}\n\
             \x20       }});\n",
            body_fn_name(d)
        ));
    }
    s.push_str(
        "\n\
         \x20       println!(\"CHURNING\");\n\
         \x20       std::future::pending::<()>().await\n\
         \x20   })\n\
         }\n",
    );
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::tree::{generate, registrations};

    #[test]
    fn test_emission_is_deterministic() {
        assert_eq!(
            emit(&generate(7), Mode::Parked),
            emit(&generate(7), Mode::Parked)
        );
        assert_eq!(
            emit(&generate(7), Mode::Churn),
            emit(&generate(7), Mode::Churn)
        );
    }

    #[test]
    fn test_every_program_has_the_fixture_skeleton() {
        for seed in 0..200 {
            let src = emit(&generate(seed), Mode::Parked);
            for needle in [
                "println!(\"READY\")",
                "allow_any_tracer",
                "census_expect::task(\"driver_00\")",
                "const TOTAL_BODIES",
                "started_rx.recv().await",
            ] {
                assert!(src.contains(needle), "seed {seed} lacks `{needle}`:\n{src}");
            }
        }
    }

    /// The emitted registration calls agree with the tree's own count —
    /// the budget the registry's capacity rests on. Registrations that
    /// run once per polled-set child instance are multiplied at
    /// runtime, so the static count is scaled through the tree walk,
    /// not by grepping the source.
    #[test]
    fn test_static_registration_sites_are_bounded() {
        for seed in 0..200 {
            let src = emit(&generate(seed), Mode::Parked);
            let sites = src.matches("census_expect::").count();
            assert!(
                sites <= registrations(&generate(seed)),
                "seed {seed}: more emitted sites than the tree accounts for"
            );
        }
    }

    /// A churn program registers nothing (a capture at an arbitrary
    /// instant can hold no address claim), never parks forever, and
    /// carries the churn skeleton instead of the readiness handshake.
    #[test]
    fn test_churn_programs_claim_nothing_and_never_settle() {
        for seed in 0..200 {
            let src = emit(&generate(seed), Mode::Churn);
            for absent in [
                "census_expect",
                "TOTAL_BODIES",
                "println!(\"READY\")",
                "std::future::pending::<u64>()",
                "std::mem::forget",
                "from_secs(3_000_000)",
                "mpsc",
            ] {
                assert!(
                    !src.contains(absent),
                    "seed {seed} churn source contains `{absent}`:\n{src}"
                );
            }
            for needle in [
                "println!(\"CHURNING\")",
                "allow_any_tracer",
                "notify.notify_waiters()",
                "sem.add_permits(4)",
                "loop {",
            ] {
                assert!(
                    src.contains(needle),
                    "seed {seed} churn source lacks `{needle}`:\n{src}"
                );
            }
        }
    }
}
