[package]
name = "libproc-sys"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "Bindings to illumos libproc, generated at build time"

[dependencies]

[target.'cfg(target_os = "illumos")'.build-dependencies]
bindgen = { version = "0.72", default-features = false }
